### ISSUE TITLE
Using as a component in form input text field - Default color

### ISSUE THREAD

**Issue by rmff** [itsjaviaguilar/bootstrap-colorpicker#176]
Hello,

I'm using colorpiker as a in line component of a input text field, similar as the examples, but when the text field is empty, colorpicker is "invisible" to user, in other words, the user don't know that there is an special button to click to select a color. There is a way to change the default color and leave the value of input text empty or any other option to let users understand that there is a color picker? I don't want to insert a dummy/stupid message like "click on gray area to pick a color"

![screenshot-mjolnic com-2016-09-09-18-10-16](https://cloud.githubusercontent.com/assets/5833880/18403002/bd28810e-76b8-11e6-92b3-56ed01b18cb7.png)

Tks!

**Comment by mjolnic** [comment]
Please, provide an example as requested in this file, which is indicated when you are opening a new issue: https://github.com/mjolnic/bootstrap-colorpicker/blob/master/CONTRIBUTING.md

**Comment by rmff** [comment]
Dears, 

Example what I'm trying to explain
http://jsfiddle.net/4ac82Lt9/

**Comment by itsjaviaguilar** [comment]
Your example is not working.

This is the proper way to create it: http://jsfiddle.net/4ac82Lt9/4/

As you can see, giving an initial css background to the `<i>` element will solve the problem.

I won't do it in the library itself, because addon backgrounds may vary depending on the used bootstrap theme.

It's up to your css to give it a default style.
